### ISSUE TITLE
Kit Optionals

### ISSUE THREAD

**Issue by jeremyworboys** [jeremyworboys/node-kit#19]
Added in CodeKit v3 RC 3

> -- The Kit language now has "optionals". They look like this: &lt;!-- $myVar? -->
> 
> -- The trailing question mark means, "If $myVar has a value, put it here. Otherwise, do nothing."
> 
> -- Kit variable names may no longer end in a '?'. This will produce an error: &lt;!-- $myVar? = something -->

**Comment by jacquesletesson** [comment]
Hello @jeremyworboys 

[gulp-kit](https://github.com/fatso83/gulp-kit) depends on node-kit so I confirm that using optional variables is not working.

Reference : https://github.com/fatso83/gulp-kit/issues/2#issuecomment-266416530

**Comment by fatso83** [comment]
I am quite certain Jeremy would accept a PR, so start hacking if you want it :-) The source is quite nice to work with and it's a very manageable size in terms of LOC.

**Comment by jeremyworboys** [comment]
Optionals have been added in version 0.10.0

**Comment by SimonWpt** [comment]
Hi @jeremyworboys Great work, thank you very much. You got a **A++** for implementing the base64 import from me :)
